name: Build

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
          with:
              node-version: 20
              cache: 'npm'
        - name: Install Dependencies
          shell: bash
          run: npm ci
        - name: Run all checks
          shell: bash
          run: npm run check
        - name: Run Tests
          shell: bash
          run: npm test
        - name: Build for Production
          shell: bash
          run: npm run build:prod
