name: Publish nRF Connect for Desktop

inputs:
    suffix:
        type: string
        required: true

runs:
    using: 'composite'
    steps:
        - name: List files
          shell: bash
          run: ls release
        - name: Publish built artifact
          uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
          with:
              name: nrfconnect-${{ inputs.suffix }}
              path: |
                  release/nrfconnect*
                  release/changelog.md
                  release/*.yml
                  !release/builder-debug.yml
